import Head from "next/head";
import Hero from "../components/Hero";

const cmd = () => {
  const data = {
    heroTitle: "CMD",
    heroText: `
      Die Abkürzung CMD steht für Craniomandibuläre Dysfunktion 
      und ist ein Überbegriff für Fehlregulationen und/ oder 
      Schmerzen der Muskel- und/oder Gelenkfunktion der Kiefergelenke.
    `,
  };
  return (
    <div>
      <Head>
        <title>CMD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero title={data.heroTitle} text={data.heroText} />
    </div>
  );
};

export default cmd;
