import Head from "next/head";
import Hero from "../components/Hero";
import PhotoText from "../components/PhotoText";
import PreeFooter from "../components/PreeFooter";
import ServiceGallery from "../components/ServiceGallery";
import SymptomBox from "../components/SymptomBox";
import styles from "../styles/Home.module.css";

export default function Home() {
  const data = {
    headline: `Sie leiden an folgenden Symptomen?`,
    text: `Jedes Krankheitsbild ist bei jedem Menschen verschieden. Schmerzen
    können viele Ursachen haben. Daher geht es mir bei jeder Behandlung um
    die ganz eigenen Bedürfnisse der Patient*innen, jede Behandlung ist
    individuell und dauert mindestens eine Stunde.Denn in der Therapie
    benötigt man eine gewisse Zeit, um sich in den Menschen
    hineinzufühlen. Das erreicht man nicht in 20 Minuten, wie es in vielen
    Praxen läuft. Jede Behandlung beginnt mit einer ausführlichen
    (professionellen) Anamnese und Befundung mit hoher Qualität.`,
    list: [
      { id: 1, title: "Unerfüllter Kinderwunsch" },
      { id: 2, title: "Unregelmäßiger Zyklus, POC, Endometriose" },
      { id: 3, title: "Fehlgeburten" },
      { id: 4, title: "Schwangerschaftsbeschwerden" },
      { id: 5, title: "Kiefergelenkschmerzen" },
      { id: 6, title: "Schlafstörungen" },
      { id: 7, title: "Stress" },
      { id: 8, title: "Kopfschmerzen, Migräne, Schwindel" },
      {
        id: 9,
        title:
          "Schmerzen im Nacken, in den Schultern, im Ellenbogen, im Handgelenk, im Rücken, in den Hüften, im Knie, in den Füßen",
      },
    ],
  };

  const personalData = {
    headline: "Sarah Radtke",
    text: `
    Mein Name ist Sarah Radtke. Ich wurde 1983 in Köln geboren, bin
    verheiratet und lebe mit meinen 2 Kindern und meinem Mann seit 2004
    in Hamburg. Nach meinen Studium der Zahnmedizin an der Uniklinik
    Eppendorf folgten eine Physiotherapieausbildung und weitere
    Qualifikationen und Fortbildungen in den Bereichen Lymphdrainage,
    Rückentraining, Kiefergelenkbehandlungen (CMD) und Manuelle
    Therapie. Heilpraktiker- und Akupunkturausbildung (Spezalisiert bei
    Kinderwunsch)
    `,
    slug: "#",
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Sarah Radtke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <ServiceGallery />
      <SymptomBox headline={data.headline} text={data.text} list={data.list} />
      <PhotoText
        headline={personalData.headline}
        text={personalData.text}
        slug={personalData.slug}
      />
      <PreeFooter site="index" />
    </div>
  );
}
