import Head from "next/head";
import React from "react";
import Hero from "../components/Hero";
import PhotoText from "../components/PhotoText";
import PreeFooter from "../components/PreeFooter";
import SymptomBox from "../components/SymptomBox";

const massage = () => {
  const data = {
    heroTitle: "Massage",
    heroText: `
        Die Massagetherapie ist eine der bekanntesten und ältesten 
        Heilmethoden und entstand aus einer griechisch-römischen Tradition. 
        Sie wird bis heute in vielen verschieden Bereichen eingesetzt.
        Die klassische Massage wird als Teil- oder Ganzkörpermassage ausgeführt 
        und kann begleitend zu anderen Behandlungsformen eingesetzt werden. 
        Vorbereitend kann Wärme (z.B. Wärmekissen, Heiße Rolle) eingesetzt werden.
      `,

    symptomTitle: "Die Massagetherapie hat folgende Auswirkungen:",
    symptomList: [
      {
        id: 1,
        title:
          "Steigerung der Durchblutung und damit bessere Ernährung des Gewebes",
      },
      { id: 2, title: "Entstauung im Lymph- und Venenbereich" },
      { id: 3, title: "Pressen, Knirschen" },
      { id: 4, title: "Regulierung des Muskeltonus" },
      { id: 5, title: "Lösung von Narben und Verklebungen im Gewebe" },
      { id: 6, title: "Schmerzlinderung" },
      { id: 7, title: "Wirkung über Reflexbogen auf die inneren Organe" },
      {
        id: 8,
        title: "Entspannung und Stabilisierung des vegetativen Nervensystem",
      },
      { id: 9, title: "Entspannung, Stressreduzierung " },
    ],

    headline:
      "Neben der klassischen Massage haben sich die unterschiedlichsten Massageformen entwickelt.",

    photoTextList: [
      {
        id: 1,
        photoTitle: "Fruchtbarkeitsmassage:",
        photoText: `
          Die Fruchtbarkeitsmassage wurde von der Gynäkologin 
          Dr. Gowri Motha (London) nach Europa gebracht. 
          Sie stellte eine deutliche höhere Schwangerschaft- 
          und Geburtenrate fest und wirkt unterstützend bei unerfüllten 
          Kinderwunsch, Menstruationsbeschwerden, Wechseljahrsbeschwerden. 
          Zudem dient sie der Entgiftung.
          `,
      },
      {
        id: 2,
        photoTitle: "Bindegewegsmassage/ Faszientherapie:",
        photoText: `
          Faszien sind das Bindegewebe unseres Körpers 
          und überall vorhanden, sie umschließen Knochen, 
          Muskeln und Organe, Sehnen und Bänder bestehen aus 
          Faszien, folglich geben sie dem Körper Halt und Form. 
          Faszien enthalten viele Nervenfasern. Bei Störungen 
          in den Faszien führt es zum Teil zu sehr starken 
          Schmerzen, bei Fehlbelastungen, zu wenig Bewegung oder 
          Stress können Faszien verkürzen und verkleben- 
          z.B. bei  unspezifischen Rückenschmerzen können 
          verklebte oder verdrehte Faszien auch die Ursache 
          sein. Mittels gezielten Faszienbehandlungen versucht 
          man diese Verklebungen/ Verdrehungen und Verkürzungen zu lösen.
          `,
        invert: true,
      },
      {
        id: 3,
        photoTitle: "Manuelle Lymphdrainage:",
        photoText: `
          Die Manuelle Lymphdrainage (MLD) zählt, wie 
          die klassische Massage und die Bindegewebsmassage, 
          zu den manuellen Therapieformen. Die Aufgabe des 
          Lymphsystems ist es, das Wasser aus dem Gewebe abzutransportieren 
          und in die Blutgefäße zurückzuführen. Bei einer Störung 
          des Lymphsystems staut sich Körperwasser im Gewebe und es 
          kann zu Schwellungen (Ödemen) kommen. Die Manuelle Lymphdrainage 
          hat positive Auswirkungen auf Ihr Immunsystem.
          `,
      },
    ],
  };

  return (
    <div>
      <Head>
        <title>Sarah Radtke | Massage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero title={data.heroTitle} text={data.heroText} />
      <SymptomBox headline={data.symptomTitle} list={data.symptomList} />
      {/* <Headline headline={data.headline} /> */}
      {data.photoTextList.map((item) => (
        <PhotoText
          key={item.id}
          headline={item.photoTitle}
          text={item.photoText}
          invert={item.invert}
        />
      ))}
      <PreeFooter site="Massage" />
    </div>
  );
};

export default massage;
