import Head from "next/head";
import React from "react";
import Hero from "../components/Hero";
import PhotoText from "../components/PhotoText";
import PreeFooter from "../components/PreeFooter";
import SymptomBox from "../components/SymptomBox";

const ueberMich = () => {
  const data = {
    heroTitle: "Sarah Radtke",
    heroText: `
      Mein Name ist Sarah Radtke. Ich wurde 1983 in Köln geboren, bin verheiratet 
      und lebe mit meinen 2 Kindern und meinem Mann seit 2004 in Hamburg.
      Nach Jahren meines Studiums der Zahnmedizin an der Uniklinik 
      Eppendorf folgten eine Physiotherapieausbildung und weitere 
      Qualifikationen und Fortbildungen in den Bereichen Lymphdrainage, 
      Rückentraining, Kiefergelenkbehandlungen (CMD) und Manuelle 
      Therapie, zudem eine Heilpraktiker- und Akupunkturausbildung 
      (spezialisiert auf Kinderwunsch).
    `,

    photoTitle: "Sie stehen im Mittelpunkt",
    photoText: `
      Seit über zehn Jahren beschäftige ich mich mit unterschiedlichen 
      Therapieansätzen und Behandlungsmöglichkeiten aus den breitgefächerten 
      Bereichen der Physiotherapie, u.a. klassische Krankengymnastik, 
      Massagetechniken, Lymphdrainage, Rückentraining, Kiefergelenkbehandlungen 
      (CMD) und der Manuellen Therapie. Ich kam irgendwann an einen Punkt, 
      an dem ich mit meinen Behandlungsmöglichkeiten auf der Stelle 
      stand und absolvierte 2015 die staatlich anerkannte Heilpraktikerprüfung. 
      Anschließend folgte die Akupunkturausbildung, um noch mehr über den 
      Tellerrand hinausschauen und weitere Therapiemöglichkeiten 
      abrufen zu können. 
    `,

    symptomText: `
      Beim Thema Kinderwunsch hatte ich selbst die Erfahrung gemacht, 
      unterstützend mit Akupunktur natürlich schwanger werden zu 
      können. In meiner eigenen Praxis bringe ich meine physiotherapeutischen 
      Erfahrungen mit ein und habe durch die Anwendung der Fruchtbarkeitsmassage 
      bereits viele Schwangerschaftserfolge erzielt.
    `,
  };

  return (
    <div>
      <Head>
        <title>Sarah Radtke | Über Mich</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero title={data.heroTitle} text={data.heroText} />
      <PhotoText headline={data.photoTitle} text={data.photoText} />
      <SymptomBox text={data.symptomText} />
      <PreeFooter site="index" />
    </div>
  );
};

export default ueberMich;
